config/routes.rb
Blocitoff::Application.routes.draw do

  devise_for :users, :controllers => { :registrations => "registrations" }

  resources :todos, only: [:destroy, :index, :new, :create, :show]

  root 'welcome#index'

end

app/models/todo.rb
class Todo < ActiveRecord::Base

  validates :description, presence: true
  validates :user, presence: true

  belongs_to :user

  def time_left
    #get the epoch created time and subtract epoch from now return days
    days_old = (Time.now - self.created_at).to_i / 86400
    days_old > 7 ? 0 : 7 - days_old
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :confirmable

  has_many :todos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protected

  def after_sign_up_path_for(resource)
    todos_path
  end

end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  #respond_to :html, :js
  before_action :authenticate_user!

  def index
    @user = current_user
    @todos = current_user.todos
  end

  def new
    @todo = Todo.new
  end

  def create
    @todo = Todo.new(todo_params)
    @todo.user = current_user
    if @todo.save
      redirect_to @todo, notice: 'Your new TODO was saved'
    else
      flash[:notice] = "Description may not be blank"
      render "new"
    end
  end

  def show
    @todo = Todo.find(params[:id])
  end

  def destroy
    # note: assume only ajax request
    @todo = Todo.find(params[:id])
    if @todo.destroy
      render nothing: true
    else
      render file: "todos/destroy.js.erb", content_type: "application/javascript"
    end
  end

private

  def todo_params
    params.require(:todo).permit(:description)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocitoff</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>


<body>
  <ul class="nav nav-tabs">
    <% if user_signed_in? %>
      <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
    <% else %>
      <li><%= link_to 'Sign in', new_user_session_path %></li>
      <li><%= link_to 'Sign up', new_user_registration_path %></li>
    <% end %>
    <li><%= link_to 'Todos', todos_path %></li>
  </ul>

  <div class="container">

    <div id="flash_container">
      <% if flash[:alert] %>
        <div class="alert alert-warning alert-dismissable">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
          <%= flash[:alert] %>
        </div>
      <% end %>
      <% if flash[:notice] %>
        <div class="alert alert-info alert-dismissable">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
          <%= flash[:notice] %>
        </div>
      <% end %>
    </div>

    <%= yield %>
  </div>

</body>
</html>

app/views/todos/destroy.js.erb
var $alert_div = $( "<div class='alert alert-warning alert-dismissable'/>");
$alert_div.html("Deletion Failure.  Please try again.");


$("#flash_container").html( $alert_div);
window.last_deleted.upper_sybling.after(window.last_deleted.item.show());
$('#' + window.last_deleted.id).prop('checked', false);

app/views/todos/index.html.haml
#content
  Todo List
  %table{ :id => "todo_table", :class => "table table-striped table-bordered table-hover"}
    %tr
      %th Description
      %th Days left
      %th complete
    - if @todos
      - @todos.each do |item|
        %tr{ :class => "row-#{item.id}" }
          %td= item.description
          %td= item.time_left
          %td= check_box_tag("#{item.id}", 'yes', false, class:"checkbox")
    %tr
      %td= link_to("Create new todo", new_todo_path)
      %td
      %td

app/views/todos/new.html.erb
<%= form_for @todo do |f| %>
  <%= f.text_field :description, placeholder: 'Desc' %>
  <%= f.submit 'Save' %>
<% end %>

app/views/todos/show.html.erb
<p><b><%= @todo.description %></b></p>

app/views/welcome/index.html.haml
.panel.panel-default
  .panel-heading
  .panel-body
    Welcome to Todos please sign up or log in.